#!/usr/bin/env bash
################################################################################
# Script: 1-world_wide_web
# Usage: ./1-world_wide_web <domain> <subdomain>
# Description: Display information about subdomains.
################################################################################

# Function to retrieve domain information
domain_information() {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

# Check the number of arguments passed
if [ "$#" == 1 ]; then
    # Retrieve information for common subdomains
    domain_information "$1" "www"
    domain_information "$1" "lb-01"
    domain_information "$1" "web-01"
    domain_information "$1" "web-02"
elif [ "$#" == 2 ]; then
    # Retrieve information for the specified subdomain
    domain_information "$1" "$2"
fi

# End of script
