#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
mkdir -p /var/www/html/
sudo chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
HOSTNAME=$(hostname)
SERVER_CONFIG=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        
        location / {
                try_files \$uri \$uri/ =404;
                add_header X-Served-By $HOSTNAME;
        }
        
        location /redirect_me {
                return 301 https://github.com/gebretewodros73;
        }

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /usr/share/nginx/html;
		internal;
	}
}"

CONFIG_FILE="/etc/nginx/sites-enabled/default"
if ! grep -qF "$SERVER_CONFIG" "$CONFIG_FILE"; then
    echo "$SERVER_CONFIG" | sudo tee -a "$CONFIG_FILE" > /dev/null
fi

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html > /dev/null

if [ "$(pgrep -c nginx)" -le 0 ]; then
        service nginx start
else
        service nginx restart
fi
