#!/usr/bin/env bash
# Update the system
apt-get -y update

# Install Nginx
apt-get -y install nginx

# Create index file with "Hello World!"
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Create custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html

# Modify Nginx configuration to include rewrite rule and custom header
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/gebretewodros73 permanent;\n\n\terror_page 404 \/custom_404.html;\n\tlocation = \/custom_404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default

sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/sites-available/default

# Start Nginx service
service nginx start

