#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y update
apt-get -y install haproxy

echo "ENABLED=1" >> /etc/default/haproxy

    echo "
        listen load_balancer
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 209964-web-01 100.25.2.154:80 check
        server 209964-web-02 100.26.175.9:80 check

    " >> /etc/haproxy/haproxy.cfg

service haproxy start
