#!/usr/bin/env bash

# Remove the default Nginx configuration from sites-enabled directory
rm /etc/nginx/sites-enabled/default

# Create a symbolic link to the default configuration in sites-available directory
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart the Nginx service to apply the changes
service nginx restart
