#!/usr/bin/env bash
# Bash script with a maximum of 5 lines (excluding the shebang) to achieve the same outcome.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
