#!/usr/bin/env bash
# Define function to handle SIGTERM and SIGQUIT signals
function cleanup {
  echo "Deleting PID file..."
  rm /var/run/myscript.pid
  exit 0
}
function no_love {
  echo "Y U no love me?!"
}
function kill_hate {
  echo "I hate the kill command"
}
trap cleanup SIGQUIT SIGTERM
trap no_love SIGINT
trap kill_hate SIGTERM
echo $$ > /var/run/myscript.pid
while true
do
echo "To infinity and beyond"
sleep 1
done
