#!/usr/bin/env bash
# display PID along with processor contains word bash
for pid in /proc/*/
do
pid=${pid//\/proc\//}
pid=${pid//\//}
if [[ -f "/proc/$pid/cmdline" ]]
then
if grep -q "bash" "/proc/$pid/cmdline"
then
echo "$pid bash"
fi
fi
done
