#!/usr/bin/env bash
# print school file exists if exists and school file not exists
if [ -e school ]
then
echo "school file exists"
if [ -s school ]
then
echo "school file is not empty"
else
echo "school file is empty"
fi
if [ -f school ]
then
echo "school is a regular file"
fi
else
echo "school file does not exist"
fi
