#!/usr/bin/env bash
# Change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts
sudo service networking restart
