#!/usr/bin/env bash
# Change localhost to 127.0.0.2 and facebook.com to 8.8.8.8
sudo sed -i 's/127.0.0.1/127.0.0.2/g;s/157.240.11.35/8.8.8.8/g' /etc/hosts
cp /etc/hosts ~/hosts.new
sudo sed -i 's/127.0.0.1/127.0.0.2/g;s/157.240.11.35/8.8.8.8/g' ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts
sudo service networking restart
